### ISSUE TITLE
Add stringout support

### ISSUE THREAD

**Issue by stephAllison** [EPICSTools/ether_ip#1]

**Comment by kasemir** [comment]
If I understand correctly, you already have this implemented and it "works".
In that case, please check that the version number gets incremented and changes.txt briefly mentions it, and go ahead to commit/merge.

**Comment by stephAllison** [comment]
Thanks.  I was getting used to the "formal" procedure of issue, branch, pull request, compare, and merge (as if the change was more extensive).  I will do that another time and follow your recommendation of a simple push and tag.
Stephanie

**Comment by kasemir** [comment]
Hi Stephanie:

Issue ticket is good. With git, branch & merge doesn't add much effort to the workflow. In fact I started to use that even if it's just me working on something all by myself, because it makes it easy to jump between the last good version and the feature I'm trying to add. But since the stringout is the only ongoing work, it's OK for you to just commit/merge that, no need to schedule the merging of multiple ongoing developments.

Thanks,
Kay

**Comment by kasemir** [comment]
ether_ip-2-27 from April 2016 includes stringent support by William Lu
