### ISSUE TITLE
Info for README

### ISSUE THREAD

**Issue by anjohnson** [EPICSTools/ether_ip#17]
Hello Kay,

I just tried building 3.2 against our Base-3.14.12.5 installation. It builds fine on Linux, RTEMS and VxWorks 6, but the VxWorks 5.5 builds fail because their compiler is too old to recognize variable definitions other than at the top of a code block, and you now have code in ether_ip.c that declares variables after other statements. I don't need to run this on VxWorks 5.5 anyway so I have removed those targets architectures from consideration in the module's CONFIG_SITE file, but you might want to add a mention of this to your README file.

Should you want to fix the code, these were my errors which I believe are all of the aforementioned variety:

```
../ether_ip.c: In function `generateTransactionId':
../ether_ip.c:71: parse error before `nn'
../ether_ip.c:76: parse error before `int'
../ether_ip.c:77: `ii' undeclared (first use in this function)
../ether_ip.c:77: (Each undeclared identifier is reported only once
../ether_ip.c:77: for each function it appears in.)
../ether_ip.c:79: `nn' undeclared (first use in this function)
../ether_ip.c: In function `dump_EncapsulationHeader':
../ether_ip.c:2027: parse error before `char'
../ether_ip.c:2028: `idtxt' undeclared (first use in this function)
../ether_ip.c: In function `make_EncapsulationHeader':
../ether_ip.c:2057: parse error before `int'
../ether_ip.c:2058: `ii' undeclared (first use in this function)
../ether_ip.c:2071: parse error before `char'
../ether_ip.c:2072: `idtxt' undeclared (first use in this function)
../ether_ip.c: In function `EIP_list_services':
../ether_ip.c:2143: parse error before `rid'
../ether_ip.c:2144: `rid' undeclared (first use in this function)
../ether_ip.c: In function `EIP_register_session':
../ether_ip.c:2210: parse error before `tid'
../ether_ip.c:2211: `tid' undeclared (first use in this function)
../ether_ip.c:2243: parse error before `rid'
../ether_ip.c:2244: `rid' undeclared (first use in this function)
../ether_ip.c: In function `EIP_unregister_session':
../ether_ip.c:2265: parse error before `tid'
../ether_ip.c:2266: `tid' undeclared (first use in this function)
../ether_ip.c: In function `EIP_Get_Attribute_Single':
../ether_ip.c:2377: parse error before `tid'
../ether_ip.c:2378: `tid' undeclared (first use in this function)
../ether_ip.c:2408: parse error before `rid'
../ether_ip.c:2409: `rid' undeclared (first use in this function)
../ether_ip.c: In function `EIP_read_tag':
../ether_ip.c:2853: parse error before `tid'
../ether_ip.c:2854: `tid' undeclared (first use in this function)
../ether_ip.c:2886: parse error before `rid'
../ether_ip.c:2887: `rid' undeclared (first use in this function)
../ether_ip.c: In function `EIP_write_tag':
../ether_ip.c:2962: parse error before `rid'
../ether_ip.c:2963: `rid' undeclared (first use in this function)
```

- Andrew

**Comment by kasemir** [comment]
Hello Andrew,

Thanks for pointing out that there's a problem with the older vxWorks 5.5 compiler.
On the other hand, I'd say that initialization on declaration, or in other words only declaring variables when they're actually needed, is generally a better pattern than the old style of bulk declarations on top, which means some variables may not be properly initialized before they're first used. Yes, by now compilers would catch that via 'not initialized' type of warnings, but overall it's more obvious and safer to declare (and right away initialize) variables when they're actually used.
Good to hear that you don't actually need to run this on vxWorks 5.5. The code has been like this for 3 years, and nobody else reported a need to run on older compilers. I assume that's in part because many people run it in a soft IOC on Linux, since a real-time OS doesn't really offer any benefit for network-based driver/device support like this one.

So for now I'd prefer to leave it as is.

**Comment by anjohnson** [comment]
> So for now I'd prefer to leave it as is.

I fully agree, I was just suggesting you put a note in the README file since that does mention that you still support Base versions back to 3.14.8.

**Comment by kasemir** [comment]
Thanks, I just added mention of vxw5.5 in there.
